---
- name: Create Authelia directories (compose, config, redis, secrets, lldap)
  file:
    path: "{{ authelia_dir }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/authelia"
    - "{{ docker_dir }}/authelia/config"
    - "{{ docker_dir }}/authelia/redis"
    - "{{ docker_dir }}/authelia/secrets/oidc/jwks"
    - "{{ docker_dir }}/lldap"
  loop_control:
    loop_var: authelia_dir

- name: Copy Authelia compose file
  template:
    src: "{{ role_path }}/templates/authelia/compose.yml"
    dest: "{{ docker_compose_dir }}/authelia/compose.yml"
    mode: "0755"

- name: Copy Authelia configuration file
  template:
    src: "{{ role_path }}/templates/authelia/configuration.yml"
    dest: "{{ docker_dir }}/authelia/config/configuration.yml"
    mode: "0755"

- name: Create Authelia JWT_SECRET file
  copy:
    content: "{{ authelia_jwt_secret }}"
    dest: "{{ docker_dir }}/authelia/secrets/JWT_SECRET"
    mode: "0755"

- name: Create Authelia SESSION_SECRET file
  copy:
    content: "{{ authelia_session_secret }}"
    dest: "{{ docker_dir }}/authelia/secrets/SESSION_SECRET"
    mode: "0755"

- name: Create Authelia STORAGE_ENCRYPTION_KEY file
  copy:
    content: "{{ authelia_storage_encryption_key }}"
    dest: "{{ docker_dir }}/authelia/secrets/STORAGE_ENCRYPTION_KEY"
    mode: "0755"

- name: Create Authelia LDAP_PASSWORD file
  copy:
    content: "{{ authelia_ldap_password }}"
    dest: "{{ docker_dir }}/authelia/secrets/LDAP_PASSWORD"
    mode: "0755"

- name: Create Authelia HMAC_SECRET file
  copy:
    content: "{{ authelia_hmac_secret }}"
    dest: "{{ docker_dir }}/authelia/secrets/HMAC_SECRET"
    mode: "0755"

- name: Copy JWKS key
  template:
    src: "{{ role_path }}/templates/authelia/rsa.2048.key"
    dest: "{{ docker_dir }}/authelia/secrets/oidc/jwks/rsa.2048.key"
    mode: "0755"
