---
- name: Create Caddy compose directory
  file:
    path: "{{ docker_compose_dir }}/caddy"
    state: directory
    mode: "0755"

- name: Copy Caddy compose file
  template:
    src: "{{ role_path }}/templates/caddy/compose.yml"
    dest: "{{ docker_compose_dir }}/caddy/compose.yml"
    mode: "0755"

- name: Create Caddy config directory
  file:
    path: "{{ docker_dir }}/caddy"
    state: directory
    mode: "0755"

- name: Copy Caddy Dockerfile
  template:
    src: "{{ role_path }}/templates/caddy/Dockerfile"
    dest: "{{ docker_dir }}/caddy/Dockerfile"
    mode: "0755"

- name: Copy Caddyfile
  template:
    src: "{{ role_path }}/templates/caddy/Caddyfile"
    dest: "{{ docker_dir }}/caddy/Caddyfile"
    mode: "0755"
