---
- name: Create Caddy compose directory
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/caddy"
    state: directory
    mode: "0755"

- name: Copy Caddy compose file
  template:
    src: ../templates/caddy/compose.yml
    dest: "{{ docker_compose_dir }}/caddy/compose.yml"

- name: Create Caddy config directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/caddy"
    state: directory
    mode: "0755"

- name: Copy Caddy Dockerfile
  template:
    src: ../templates/caddy/Dockerfile
    dest: "{{ docker_dir }}/caddy/Dockerfile"

- name: Copy Caddyfile
  template:
    src: ../templates/caddy/Caddyfile
    dest: "{{ docker_dir }}/caddy/Caddyfile"
