---
- name: Create cloudflare-ddns directories (compose, config)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/cloudflare-ddns"
    - "{{ docker_dir }}/cloudflare-ddns"

- name: Copy cloudflare-ddns compose file
  template:
    src: "{{ role_path }}/templates/cloudflare-ddns/compose.yml"
    dest: "{{ docker_compose_dir }}/cloudflare-ddns/compose.yml"
    mode: "0755"

- name: Copy cloudflare-ddns config.json
  template:
    src: "{{ role_path }}/templates/cloudflare-ddns/config.json"
    dest: "{{ docker_dir }}/cloudflare-ddns/config.json"
    mode: "0755"
