---
- name: Create dashdot compose directory
  file:
    path: "{{ docker_compose_dir }}/dashdot"
    state: directory
    mode: "0755"

- name: Copy dashdot compose file
  template:
    src: "{{ role_path }}/templates/dashdot/compose.yml"
    dest: "{{ docker_compose_dir }}/dashdot/compose.yml"
    mode: "0755"

- name: Create dashdot directory
  file:
    path: "{{ docker_dir }}/dashdot"
    state: directory
    mode: "0755"
