---
- name: Create dashdot directories (compose, config)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/dashdot"
    - "{{ docker_dir }}/dashdot"

- name: Copy dashdot compose file
  template:
    src: "{{ role_path }}/templates/dashdot/compose.yml"
    dest: "{{ docker_compose_dir }}/dashdot/compose.yml"
    mode: "0755"
