---
- name: Create Immich compose directory
  file:
    path: "{{ docker_compose_dir }}/immich"
    state: directory
    mode: "0755"

- name: Copy Immich compose file
  template:
    src: "{{ role_path }}/templates/immich/compose.yml"
    dest: "{{ docker_compose_dir }}/immich/compose.yml"
    mode: "0755"

- name: Copy Immich env file
  template:
    src: "{{ role_path }}/templates/immich/.env"
    dest: "{{ docker_compose_dir }}/immich/.env"
    mode: "0755"

- name: Create Immich DB directory
  file:
    path: "{{ docker_dir }}/immich/postgres"
    state: directory
    mode: "0755"

- name: Create Immich upload directory
  file:
    path: "{{ nas_mount }}/personal/Photos/Immich"
    state: directory
    mode: "0755"
