---
- name: Create Immich directories (compose, db) (read-only)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/immich"
    - "{{ docker_dir }}/immich/postgres"

- name: Create Immich directories (upload) (read-write)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0777"
  loop:
    - "{{ nas_mount }}/personal/Pictures/Immich"
    - "{{ nas_mount }}/personal/Pictures/Immich/upload"
    - "{{ nas_mount }}/personal/Pictures/Immich/library"
    - "{{ nas_mount }}/personal/Pictures/Immich/thumbs"
    - "{{ nas_mount }}/personal/Pictures/Immich/encoded-video"
    - "{{ nas_mount }}/personal/Pictures/Immich/profile"
    - "{{ nas_mount }}/personal/Pictures/Immich/backups"

- name: Create .immich file in each directory
  copy:
    content: ""
    dest: "{{ item }}/.immich"
    mode: "0777"
  loop:
    - "{{ nas_mount }}/personal/Pictures/Immich/upload"
    - "{{ nas_mount }}/personal/Pictures/Immich/library"
    - "{{ nas_mount }}/personal/Pictures/Immich/thumbs"
    - "{{ nas_mount }}/personal/Pictures/Immich/encoded-video"
    - "{{ nas_mount }}/personal/Pictures/Immich/profile"
    - "{{ nas_mount }}/personal/Pictures/Immich/backups"

- name: Copy Immich compose file
  template:
    src: "{{ role_path }}/templates/immich/compose.yml"
    dest: "{{ docker_compose_dir }}/immich/compose.yml"
    mode: "0755"

- name: Copy Immich env file
  template:
    src: "{{ role_path }}/templates/immich/.env"
    dest: "{{ docker_compose_dir }}/immich/.env"
    mode: "0755"
