---
- name: Create Immich directories (compose, db, upload)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/immich"
    - "{{ docker_dir }}/immich/postgres"
    - "{{ nas_mount }}/personal/Photos/Immich"

- name: Copy Immich compose file
  template:
    src: "{{ role_path }}/templates/immich/compose.yml"
    dest: "{{ docker_compose_dir }}/immich/compose.yml"
    mode: "0755"

- name: Copy Immich env file
  template:
    src: "{{ role_path }}/templates/immich/.env"
    dest: "{{ docker_compose_dir }}/immich/.env"
    mode: "0755"
