---
- name: Create Jellyfin compose directory
  file:
    path: "{{ docker_compose_dir }}/jellyfin"
    state: directory
    mode: "0755"

- name: Copy Jellyfin compose file
  template:
    src: "{{ role_path }}/templates/jellyfin/compose.yml"
    dest: "{{ docker_compose_dir }}/jellyfin/compose.yml"
    mode: "0755"

- name: Create Jellyfin config directory
  file:
    path: "{{ docker_dir }}/jellyfin/config"
    state: directory
    mode: "0755"

- name: Create Jellyfin cache directory
  file:
    path: "{{ docker_dir }}/jellyfin/cache"
    state: directory
    mode: "0755"
