---
- name: Get getent command output for render group
  command: getent group render
  register: getent_render
  changed_when: false

- name: Extract GID from getent output
  set_fact:
    gid_render: "{{ getent_render.stdout.split(':')[2] }}"

- name: Create Jellyfin compose directory
  file:
    path: "{{ docker_compose_dir }}/jellyfin"
    state: directory
    mode: "0755"

- name: Copy Jellyfin compose file
  template:
    src: "{{ role_path }}/templates/jellyfin/compose.yml"
    dest: "{{ docker_compose_dir }}/jellyfin/compose.yml"
    mode: "0755"
  vars:
    - gid_render: "{{ gid_render }}"

- name: Create Jellyfin config directory
  file:
    path: "{{ docker_dir }}/jellyfin/config"
    state: directory
    mode: "0755"

- name: Create Jellyfin cache directory
  file:
    path: "{{ docker_dir }}/jellyfin/cache"
    state: directory
    mode: "0755"
