---
- name: Create Jellyfin directories (compose, config, cache)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/jellyfin"
    - "{{ docker_dir }}/jellyfin"

- name: Get getent command output for render group
  command: getent group render
  register: getent_render
  changed_when: false

- name: Extract GID from getent output
  set_fact:
    gid_render: "{{ getent_render.stdout.split(':')[2] }}"

- name: Copy Jellyfin compose file
  template:
    src: "{{ role_path }}/templates/jellyfin/compose.yml"
    dest: "{{ docker_compose_dir }}/jellyfin/compose.yml"
    mode: "0755"
