---
- name: Create Nextcloud directories (compose, config, db, data)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/nextcloud"
    - "{{ docker_dir }}/nextcloud/config"
    - "{{ docker_dir }}/nextcloud/db"
    - "{{ nas_mount }}/nextcloud_data"

- name: Copy Nextcloud compose file
  template:
    src: "{{ role_path }}/templates/nextcloud/compose.yml"
    dest: "{{ docker_compose_dir }}/nextcloud/compose.yml"
    mode: "0755"
