---
- name: Create Nextcloud compose directory
  file:
    path: "{{ docker_compose_dir }}/nextcloud"
    state: directory
    mode: "0755"

- name: Copy Nextcloud compose file
  template:
    src: "{{ role_path }}/templates/nextcloud/compose.yml"
    dest: "{{ docker_compose_dir }}/nextcloud/compose.yml"
    mode: "0755"

- name: Create Nextcloud config directory
  file:
    path: "{{ docker_dir }}/nextcloud"
    state: directory
    mode: "0755"
