---
- name: Create Nextcloud compose directory
  ansible.builtin.file:
    path: "{{ docker_compose_dir }}/nextcloud"
    state: directory
    mode: "0755"

- name: Copy Nextcloud compose file
  template:
    src: ../templates/nextcloud/compose.yml
    dest: "{{ docker_compose_dir }}/nextcloud/compose.yml"

- name: Create Nextcloud config directory
  ansible.builtin.file:
    path: "{{ docker_dir }}/nextcloud"
    state: directory
    mode: "0755"
