---
- name: Create Piped directories (compose, config, db)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}/piped"
    - "{{ docker_dir }}/piped/config"
    - "{{ docker_dir }}/piped/data/db"

- name: Copy Piped compose file
  template:
    src: "{{ role_path }}/templates/piped/compose.yml"
    dest: "{{ docker_compose_dir }}/piped/compose.yml"
    mode: "0755"

- name: Find all piped config files in templates folder
  find:
    paths: "{{ role_path }}/templates/piped/config"
    file_type: file
  register: found_files

- name: Copy Piped config files
  template:
    src: "{{ role_path }}/templates/piped/config/{{ item }}"
    dest: "{{ docker_dir }}/piped/config{{ item }}"
    mode: "0755"
  with_items: "{{ found_files.files | map(attribute='path') | map('basename') | list }}"

- name: Copy Piped feed update script to bin directory
  template:
    src: "{{ role_path }}/templates/piped/update_piped_feed.sh"
    dest: "/home/{{ username }}/bin/update_piped_feed.sh"
    mode: "0755"

- name: Create Piped feed cron job
  cron:
    name: "Periodically update Piped feed (every 15 minutes)"
    minute: "*/15"
    hour: "*"
    job: "/home/{{ username }}/bin/update_piped_feed.sh"
    state: present
