---
- name: Create Syncthing compose directory
  file:
    path: "{{ docker_compose_dir }}/syncthing"
    state: directory
    mode: "0755"

- name: Create Syncthing config directory
  file:
    path: "{{ docker_compose_dir }}/syncthing/config"
    state: directory
    mode: "0755"

- name: Copy Syncthing compose file
  template:
    src: "{{ role_path }}/templates/syncthing/compose.yml"
    dest: "{{ docker_compose_dir }}/syncthing/compose.yml"
    mode: "0755"

- name: Check if NAS mount exists
  stat:
    path: "{{ nas_mount }}"
  register: dir_stat

- name: Fail if NAS mount doesn't exist
  fail:
    masg: "The directory {{ nas_mount }} does not exist. Make sure the drive is mounted and formatted properly!"
  when: not dir_stat.stat.exists

- name: Create personal directory that will be used for Syncthing
  file:
    path: "{{ nas_mount }}/personal"
    state: directory
    mode: "0755"
