---
services:
  broker:
    container_name: paperless_redis
    image: docker.io/library/redis:8
    restart: unless-stopped
    volumes:
      - "{{ docker_dir }}/paperless/redis:/data"

  db:
    container_name: paperless_db
    image: docker.io/library/mariadb:11
    restart: unless-stopped
    volumes:
      - "{{ docker_dir }}/paperless/db:/var/lib/mysql"
    environment:
      MARIADB_HOST: paperless
      MARIADB_DATABASE: paperless
      MARIADB_USER: paperless
      MARIADB_PASSWORD: "{{ paperless_db_password }}"
      MARIADB_ROOT_PASSWORD: "{{ paperless_db_root_password }}"

  webserver:
    container_name: paperless_webserver
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    depends_on:
      - db
      - broker
    ports:
      - "8010:8000"
    volumes:
      - "{{ nas_mount }}/apps/paperless/data:/usr/src/paperless/data"
      - "{{ nas_mount }}/apps/paperless/media:/usr/src/paperless/media"
      - "{{ docker_dir }}/paperless/export:/usr/src/paperless/export"
      - "{{ docker_dir }}/paperless/consume:/usr/src/paperless/consume"
    env_file: docker-compose.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBENGINE: mariadb
      PAPERLESS_DBHOST: db
      PAPERLESS_DBUSER: paperless
      PAPERLESS_DBPASS: "{{ paperless_db_password }}"
      PAPERLESS_DBPORT: 3306
      PAPERLESS_APPS: "allauth.socialaccount.providers.openid_connect"
      PAPERLESS_SOCIALACCOUNT_PROVIDERS: '{"openid_connect":{"SCOPE":["openid","profile","email"],"OAUTH_PKCE_ENABLED":true,"APPS":[{"provider_id":"authelia","name":"Authelia","client_id":"{{ authelia_paperless_cid }}","secret":"{{ authelia_paperless_secret }}","settings":{"server_url":"https://auth.{{ domain_public }}","token_auth_method":"client_secret_basic"}}]}}'
