---
services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    environment:
      PORT: 45876
    env_file:
      - .env # put public key that's shown in the web ui in there with KEY='<public_key>'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
{% for disk in disk_config | default([]) %}
      - "{{ disk.mountpoint }}/.beszel:/extra-filesystems/{% set device = (beszel_disk_mapping | selectattr('wwn', 'equalto', disk.wwn) | map(attribute='device') | first) %}{{ device | default(disk.name) | basename }}:ro"
{% endfor %}
