---
- hosts: srv_clara # raspberry pi; raspbian
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers
    - role: mail_alerts
      tags:
        - mail_alerts

- hosts: srv__rosa # x86_64; debian
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: storageconf # disable, if needed
      tags:
        - storageconf
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers
    - role: mail_alerts
      tags:
        - mail_alerts

- hosts: test_host
  become: true
  roles:
    - role: storageconf
      tags:
        - storageconf
