---
- hosts: srv_clara # server; raspberry pi; raspbian
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers
    - role: mail_alerts
      tags:
        - mail_alerts

- hosts: srv_rosa # server; x86_64; debian
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: storageconf # disable, if needed
      tags:
        - storageconf
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers
    - role: mail_alerts
      tags:
        - mail_alerts

- hosts: pc_karl # workstation, x86_64; fedora
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: desktop_suite
      tags:
        - desktop_suite
    - role: geerlingguy.docker
      tags:
        - docker

- hosts: pc_rudi # notebook, x86_64; fedora
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: desktop_suite
      tags:
        - desktop_suite
    - role: geerlingguy.docker
      tags:
        - docker

- hosts: test_host
  become: true
  roles:
    - role: storageconf
      tags:
        - storageconf
