---
- hosts: srv_clara
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers

- hosts: srv__rosa
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: storageconf # disable, if needed
      tags:
        - storageconf
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers

- hosts: test_host
  become: true
  roles:
    - role: storageconf
      tags:
        - storageconf
