---
- hosts: raspi_clara
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers

- hosts: main_rosa
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers
