---
- name: "Deployment: clara; server; raspberry pi; raspbian"
  hosts: srv_clara
  become: true
  roles:
    - role: mail_alerts_disable
      tags:
        - mail_alerts_disable
    - role: system
      tags:
        - system
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: mail_alerts
      tags:
        - mail_alerts

- name: "Deployment: rosa; server; x86_64; debian"
  hosts: srv_rosa
  become: true
  roles:
    - role: mail_alerts_disable
      tags:
        - mail_alerts_disable
    - role: system
      tags:
        - system
    - role: storageconf # disable, if needed
      tags:
        - storageconf
    - role: geerlingguy.security
      tags:
        - security
    - role: geerlingguy.docker
      tags:
        - docker
    - role: containers
      tags:
        - containers
    - role: srv_cronjobs
      tags:
        - srv_cronjobs
    - role: mail_alerts
      tags:
        - mail_alerts

- name: "Deployment: karl; workstation, x86_64; fedora"
  hosts: pc_karl
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: desktop_suite
      tags:
        - desktop_suite
    - role: geerlingguy.docker
      tags:
        - docker

- name: "Deployment: rudi; notebook, x86_64; fedora"
  hosts: pc_rudi
  become: true
  roles:
    - role: system
      tags:
        - system
    - role: desktop
      tags:
        - desktop
    - role: geerlingguy.docker
      tags:
        - docker

- name: "Deployment: test host; local vm"
  hosts: test_host
  become: true
  roles:
    - role: storageconf
      tags:
        - storageconf
