---
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel-hub
    restart: unless-stopped
    environment:
      - USER_CREATION=true
    extra_hosts:
      - host.docker.internal:host-gateway
    ports:
      - 8090:8090
    volumes:
      - "{{ docker_dir }}/beszel_data:/beszel_data"
