---
- name: Debloating (uninstalling unused apps)
  dnf:
    name:
      - kdump-anaconda-addon
      - anaconda
      - gnome-contacts
      - gnome-maps
      - gnome-system-monitor
      - gnome-tour
      - libreoffice-*
      - libreoffice
      - mediawriter
      - ptyxis
      - rhythmbox
      - totem
      - unoconv
      - yelp
    state: absent
    autoremove: true
