---
- name: Installing Microsoft core fonts
  block:
    - name: Installing required packages
      dnf:
        name:
          - curl
          - cabextract
          - xorg-x11-font-utils
          - fontconfig
        state: present

    - name: Install corefonts package
      dnf:
        name: "https://downloads.sourceforge.net/project/mscorefonts2/rpms/msttcore-fonts-installer-2.6-1.noarch.rpm"
        state: present
        disable_gpg_check: true

- name: Install Jetbrains Mono Nerd Font
  block:
    - name: Create font directory
      file:
        path: "/usr/share/fonts/truetype/JetBrainsMono"
        state: directory
        mode: "0755"

    - name: Download .tff
      get_url:
        url: "https://github.com/ryanoasis/nerd-fonts/raw/refs/heads/master/patched-fonts/JetBrainsMono/Ligatures/Regular/JetBrainsMonoNerdFontMono-Regular.ttf"
        dest: "/usr/share/fonts/truetype/JetBrainsMono/JetBrainsMonoNerdFontMono-Regular.ttf"

    - name: Update font cache
      command: fc-cache -f -v

- name: Installing remaining fonts
  dnf:
    name:
      - comic-neue-fonts
      - default-fonts-cjk
      - google-arimo-fonts
      - google-roboto-fonts
    state: present
