---
- name: Ensure ~/.local/share/icons exists
  file:
    path: "/home/{{ username }}/.local/share/icons"
    state: directory
    mode: "0775"
    owner: "{{ username }}"
    group: "{{ username }}"

- name: Install cursor (bibata)
  block:
    - name: Enable the dnf copr repository
      community.general.copr:
        name: peterwu/rendezvous
        state: enabled

    - name: Install cursor via dnf
      dnf:
        name: bibata-cursor-themes
        state: present

- name: Install icon pack (morewaita)
  block:
    - name: Enable the dnf copr repository
      community.general.copr:
        name: dusansimic/themes

    - name: Install icon theme via dnf
      dnf:
        name: morewaita-icon-theme
        state: present

- name: Tweak gsettings
  block:
    - name: Enable minimize and maximize button to window title bar
      command: "gsettings set org.gnome.desktop.wm.preferences button-layout 'close,minimize,maximize:'"
      changed_when: false

    - name: Enable cursor
      command: "gsettings set org.gnome.desktop.interface cursor-theme 'Bibata-Modern-Ice'"
      changed_when: false

    - name: Enable icon pack
      command: "gsettings set org.gnome.desktop.interface icon-theme 'MoreWaita'"
      changed_when: false
