---
services:
  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      # - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
      {% for disk in disk_config %}
      - "{{ disk.mountpoint }}/.beszel:/extra-filesystems/{{ disk.name }}:ro"
      {% endfor %}
    environment:
      PORT: 45876
      KEY: "public key: change according to web ui dialog"
