---
- name: Debloating (uninstalling unused apps)
  dnf:
    name:
      - anaconda
      - gnome-contacts
      - gnome-maps
      - gnome-tour
      - libreoffice-core
      - mediawriter
      - rythmbox
      - totem
      - unoconv
      - yelp
    state: absent
