---
services:
  samba:
    image: dockurr/samba
    container_name: samba
    environment:
      NAME: "Data"
      USER: "{{ username }}"
      PASS: "{{ samba_password }}"
    ports:
      - 445:445
    volumes:
      - "{{ nas_mount }}/personal:/storage"
    restart: unless-stopped
