---
- name: Copy service file to host
  template:
    src: "{{ role_path }}/templates/hdparm_spin_down.service"
    dest: /etc/systemd/sytem/hdparm_spin_down.service
    mode: "0644"

- name: Enable service file
  systemd:
    name: hdparm_spin_down
    enabled: true
    state: started
