---
- name: Install hdparm
  apt:
    name: hdparm
    state: present

- name: Modify hdparm.conf
  block:
    - name: Create hdparm.conf file
      file:
        path: /etc/hdparm.conf
        state: touch
        mode: "0644"

    - name: Append to hdparm.conf
      lineinfile:
        path: /etc/hdparm.conf
        line: |
          /dev/disk/by-id/wwn-{{ item.wwn }} {
            spindown_time = 25
          }
        state: present
      loop: "{{ disk_config }}"
      when: item.type == "hdd"
