---
- name: Install ZFS
  include_tasks: zfs_install.yml

- name: Create ZFS pools
  include_tasks: zfs_pool_creation.yml

- name: Enable necessary ZFS services and reboot
  include_tasks: zfs_services_enable.yml

- name: Install and configure mergerfs with uncaching script
  include_tasks: mergerfs.yml

- name: Install and enable hdparm spindown systemd service
  include_tasks: hdparm_spin_down.yml
