---
- name: Install mergerfs
  apt:
    name: mergerfs
    state: present

- name: Copy service file to host
  template:
    src: "{{ role_path }}/templates/mergerfs_media.service"
    dest: /etc/systemd/system/mergerfs_media.service
    mode: "0644"

- name: Enable service file
  systemd:
    name: mergerfs_media
    enabled: true
    state: started

- name: Move uncaching script to bin directory
  template:
    src: "{{ role_path }}/templates/uncache.py"
    dest: "/home/{{ username }}/bin/uncache.py"
    mode: "0755"

- name: Create uncaching cron job for shows directory
  cron:
    name: Perdiodically run uncaching script for shows directory (every hour)
    minute: "0"
    hour: "*"
    job: "python3 /home/{{ username }}/bin/uncache.py -s /mnt/media_cache/shows -d /mnt/media_main/shows -t 85"
    state: present

- name: Create uncaching cron job for movies directory
  cron:
    name: Perdiodically run uncaching script for movies directory (every hour)
    minute: "30"
    hour: "*"
    job: "python3 /home/{{ username }}/bin/uncache.py -s /mnt/media_cache/movies -d /mnt/media_main/movies -t 83"
    state: present
