---
- name: Install mergerfs
  apt:
    name: mergerfs
    state: present

- name: Copy service file to host
  template:
    src: "{{ role_path }}/templates/mergerfs_media.service"
    dest: /etc/systemd/sytem/mergerfs_media.service
    mode: "0644"
  var:
    mergerfs_media_dir: "{{ mergerfs_media_dir }}"

- name: Enable service file
  systemd:
    name: mergerfs_media
    enabled: true
    state: started

- name: Move uncaching script to bin directory
  template:
    src: "{{ role_path }}/templates/uncache.py"
    dest: "/home/{{ username }}/bin/uncache.py"
    mode: "0755"

- name: Create uncaching cron job
  cron:
    name: Perdiodically run uncaching script (every hour)
    minute: "0"
    hour: "*"
    job: "python3 /home/{{ username }}/bin/uncache.py"
    state: present
