---
- name: Enable zfs-load-key service
  systemd:
    name: zfs-load-key
    enabled: true
    state: started

- name: Enable zfs-mount service
  systemd:
    name: zfs-mount
    enabled: true
    state: started

- name: Get list of ZFS pools
  command: zpool list -H -o name
  register: zfs_pools
  changed_when: false

- name: Enable zfs-import service for all ZFS pools
  systemd:
    name: "zfs-import@{{ item }}"
    enabled: true
    state: started
  loop: "{{ zfs_pools.stdout_lines }}"
  when: zfs_pools.stdout_lines | length > 0 # Only run if there are pools

- name: Copy ZFS backup script to bin directory
  template:
    src: "{{ role_path }}/templates/zfs_backup.sh"
    dest: "/usr/local/sbin/zfs_backup.sh"
    owner: root
    group: root
    mode: "0700"

- name: Create ZFS backup cron job
  cron:
    name: "Periodically backup zfs nas pool to backup pool (every day at 11:00)"
    minute: "0"
    hour: "11"
    job: "/usr/local/sbin/zfs_backup.sh"
    state: present

- name: Reboot
  reboot:
    msg: Rebooting enabling ZFS services
