---
- name: Enable zfs-load-key service
  block:
    - name: Check if zfs-load-key service is masked
      stat:
        path: /lib/systemd/system/zfs-load-key.service
      register: zfs_load_key_service

    - name: Unmask zfs-load-key service
      command: unlink /lib/systemd/system/zfs-load-key.service
      when: zfs_load_key_service.stat.exists == true
      changed_when: true

    - name: Reload systemd daemon
      command: systemctl daemon-reload

    - name: Enable the service
      systemd:
        name: zfs-load-key
        masked: false
        state: started
        enabled: true

- name: Enable zfs-mount service
  systemd:
    name: zfs-mount
    enabled: true
    state: started

- name: Copy ZFS backup script to bin directory
  template:
    src: "{{ role_path }}/templates/zfs_backup.sh"
    dest: "/usr/local/sbin/zfs_backup.sh"
    owner: root
    group: root
    mode: "0700"

- name: Create ZFS backup cron job
  cron:
    name: "Periodically backup zfs nas pool to backup pool (every day at 11:00)"
    minute: "0"
    hour: "11"
    job: "/usr/local/sbin/zfs_backup.sh"
    state: present

- name: Reboot if user confirms
  block:
    - name: Ask for confirmation before rebooting
      pause:
        prompt: "Do you want to reboot the system to enable ZFS services? (y/n)"
      register: reboot_confirmation

    - name: Reboot the system
      reboot:
        msg: "Rebooting to enable ZFS services"
      when: reboot_confirmation.user_input | lower == 'y'
