---
# about
username: bloom
hostname: "{{ inventory_hostname }}"

# docker directories
docker_dir: /opt/docker/data
docker_compose_dir: /opt/docker/compose

# SSH (geerlingguy.security)
security_ssh_allowed_users: ["{{ username }}"]
security_autoupdate_enabled: true
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "03:00"
security_fail2ban_enabled: true

# network
domain_public: blccm.ing
domain_local: "lab.{{ domain_public }}"

# package packs (flatpak)
pkgs_flatpaks_office: &pkgs_flatpaks_office
  - app.zen_browser.zen
  - dev.vencord.Vesktop
  - io.anytype.anytype
  - md.obsidian.Obsidian
  - net.ankiweb.Anki
  - org.keepassxc.KeePassXC
  - org.localsend.localsend_app
  - org.mozilla.Thunderbird
  - org.onlyoffice.desktopeditors
  - org.signal.Signal
  - org.torproject.torbrowser-launcher

pkgs_flatpak_dev: &pkgs_flatpak_dev
  - cc.arduino.IDE2
  - com.emqx.MQTTX
  - com.visualstudio.code-oss
  - dev.zed.Zed
  - org.raspberrypi.rpi-imager

pkg_flatpak_gaming: &pkgs_flatpak_gaming
  - com.usebottles.bottles
  - com.valvesoftware.Steam
  - org.prismlauncher.PrismLauncher

pkgs_flatpak_gnome: &pkgs_flatpak_gnome
  - com.mattjakeman.ExtensionManager
  - com.raggesilver.BlackBox
  - io.missioncenter.MissionCenter
  - page.tesk.Refine

pkgs_flatpak_media: &pkgs_flatpak_media
  - org.gimp.GIMP
  - org.videolan.VLC
  - io.github.josephmawa.Bella

pkgs_flatpak_media_ext: &pkgs_flatpak_media_ext
  - com.obsproject.Studio
  - com.transmissionbt.Transmission
  - org.audacityteam.Audacity
  - org.nicotine_plus.Nicotine

# package packs (dnf)
pkgs_dnf_dev: &pkgs_dnf_dev
  - git
  - python3

pkgs_dnf_office: &pkgs_dnf_office
  - gnuplot
  - texlive-scheme-full
