# misc
username: phlourish

hostname: "{{ inventory_hostname }}"

extra_packages: 
  - btop
  - powertop

# docker
docker_dir: /opt/docker/data

docker_compose_dir: /opt/docker/compose

# SSH (geerlingguy.security)
security_ssh_allowed_users: ["{{ username }}"]
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "03:00"
security_fail2ban_enabled: true