---
# about
username: bloom
hostname: "{{ inventory_hostname }}"

# docker directories
docker_dir: /opt/docker/data
docker_compose_dir: /opt/docker/compose

# SSH (geerlingguy.security)
security_ssh_allowed_users: ["{{ username }}"]
security_autoupdate_enabled: true
security_autoupdate_reboot: true
security_autoupdate_reboot_time: "03:00"
security_fail2ban_enabled: true

# network
domain_public: blccm.ing
domain_local: "lab.{{ domain_public }}"

# package packs (flatpak)
pkgs_flatpaks_office:
  - app.zen_browser.zen
  - dev.vencord.Vesktop
  - md.obsidian.Obsidian
  - org.keepassxc.KeePassXC
  - org.localsend.localsend_app
  - org.mozilla.Thunderbird
  - org.onlyoffice.desktopeditors
  - org.signal.Signal
  - org.torproject.torbrowser-launcher

pkgs_flatpak_dev:
  - com.visualstudio.code-oss
  - dev.zed.Zed

pkg_flatpak_gaming:
  - com.usebottles.bottles
  - org.prismlauncher.PrismLauncher

pkgs_flatpak_gnome:
  - com.mattjakeman.ExtensionManager
  - page.tesk.Refine

pkgs_flatpak_media:
  - org.gimp.GIMP
  - org.videolan.VLC
  - io.github.josephmawa.Bella

pkgs_flatpak_media_ext:
  - com.obsproject.Studio
  - com.transmissionbt.Transmission
  - org.audacityteam.Audacity
  - org.nicotine_plus.Nicotine

# package packs (dnf)
pkgs_dnf_dev:
  - git
  - python3

pkgs_dnf_gaming:
  - steam

pkgs_dnf_office:
  - gnuplot
  - texlive-scheme-full
