---
services:
  authelia:
    container_name: "authelia"
    image: "docker.io/authelia/authelia:latest"
    restart: "unless-stopped"
    ports:
      - "9091:9091"
    environment:
      AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET_FILE: "/secrets/JWT_SECRET"
      AUTHELIA_SESSION_SECRET_FILE: "/secrets/SESSION_SECRET"
      AUTHELIA_STORAGE_ENCRYPTION_KEY_FILE: "/secrets/STORAGE_ENCRYPTION_KEY"
      AUTHELIA_AUTHENTICATION_BACKEND_LDAP_PASSWORD_FILE: "/secrets/LDAP_PASSWORD"
    volumes:
      - "{{ docker_dir }}/authelia/config:/config"
      - "{{ docker_dir }}/authelia/secrets:/secrets"
    depends_on:
      - lldap
      - redis

  redis:
    container_name: "authelia-redis"
    image: "redis:alpine"
    volumes:
      - "{{ docker_dir }}/authelia/redis:/data"
    restart: "unless-stopped"
    environment:
      TZ: "Europe/Berlin"

  lldap:
    container_name: "authelia-lldap"
    image: lldap/lldap:stable
    restart: "unless-stopped"
    ports:
      - "17170:17170" # web ui
    volumes:
      - "{{ docker_dir }}/lldap:/data"
      - "{{ docker_dir }}/authelia/secrets:/secrets"
    environment:
      TZ: "Europe/Berlin"
      LLDAP_LDAP_BASE_DN: "DC={{ domain_local.split('.')[1] }},DC={{ domain_local.split('.')[2] }}"
      LLDAP_JWT_SECRET_FILE: "/secrets/JWT_SECRET"
      LLDAP_LDAP_USER_PASS_FILE: "/secrets/LDAP_PASSWORD"
      LLDAP_LDAP_PORT: 389
