server:
  address: "tcp://:9091"
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"
        authn_strategies:
          - name: "HeaderAuthorization"
            schemes:
              - "Basic"
          - name: "CookieSession"
      ext-authz:
        implementation: "ExtAuthz"
        authn_strategies:
          - name: "HeaderAuthorization"
            schemes:
              - "Basic"
          - name: "CookieSession"
      auth-request:
        implementation: "AuthRequest"
        authn_strategies:
          - name: "HeaderAuthorization"
            schemes:
              - "Basic"
          - name: "CookieSession"
      legacy:
        implementation: "Legacy"
        authn_strategies:
          - name: "HeaderLegacy"
          - name: "CookieSession"

totp:
  disable: false
  issuer: "auth.{{ public_domain }}"

authentication_backend:
  ldap:
    address: "ldap://127.0.0.1" # using local lldap
    implementation: "lldap"
    timeout: "5s"
    start_tls: false
    base_dn: "DC={{ domain_local.split('.')[1] }},DC={{ domain_local.split('.')[2] }}"
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    groups_filter: "(&(member={dn})(objectClass=groupOfNames))"
    group_search_mode: "filter"
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: "CN=admin,DC={{ local_domain | split('.') | first }},DC={{ local_domain | split('.') | last }}"

access_control:
  default_policy: deny
  rules:
    - domain: "auth.{{ domain_public }}"
      policy: "two_factor"
    - domain: "crg.{{ domain_public }}"
      policy: "one_factor"
    - domain: "cloud.{{ domain_public }}"
      policy: "two_factor"
    - domain: "fin.{{ domain_local }}"
      policy: "one_factor"
    - domain: "imch.{{ domain_local }}"
      policy: "one_factor"
    - domain: "sync.{{ domain_local }}"
      policy: "two_factor"
    - domain: "trans.{{ domain_local }}"
      policy: "one_factor"
    - domain: "srr.{{ domain_local }}"
      policy: "one_factor"
    - domain: "rrr.{{ domain_local }}"
      policy: "one_factor"
    - domain: "prr.{{ domain_local }}"
      policy: "one_factor"
    # piped, homarr, homeassistant

session:
  cookies:
    - name: "authelia_session"
      domain: "{{ domain_public }}"
      authelia_url: "auth.{{ domain_public }}"
      default_redirection_url: "{{ domain_public }}"
      expiration: "3 hours"
      inactivity: "30 minutes"

redis:
  host: "redis"
  port: 6379

regulation:
  max_retries: 5
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  local:
    path: "/config/db.sqlite3"
