---
server:
  address: "tcp://:9091"
  endpoints:
    authz:
      forward-auth:
        implementation: "ForwardAuth"

totp:
  disable: false
  issuer: "auth.{{ domain_public }}"

authentication_backend:
  ldap:
    address: "ldap://lldap" # using local lldap
    implementation: "lldap"
    timeout: "5s"
    start_tls: false
    base_dn: "DC={{ domain_local.split('.')[1] }},DC={{ domain_local.split('.')[2] }}"
    users_filter: "(&({username_attribute}={input})(objectClass=person))"
    groups_filter: "(&(member={dn})(objectClass=groupOfNames))"
    group_search_mode: "filter"
    permit_referrals: false
    permit_unauthenticated_bind: false
    user: "UID=admin,OU=people,DC={{ domain_local.split('.')[1] }},DC={{ domain_local.split('.')[2] }}"

access_control:
  default_policy: deny
  rules:
    - domain: "auth.{{ domain_public }}"
      policy: "two_factor"
    - domain: "crg.{{ domain_public }}"
      policy: "one_factor"
    - domain: "cloud.{{ domain_public }}"
      policy: "two_factor"
    - domain: "fin.{{ domain_local }}"
      policy: "one_factor"
    - domain: "imch.{{ domain_local }}"
      policy: "one_factor"
    - domain: "sync.{{ domain_local }}"
      policy: "two_factor"
    - domain: "trans.{{ domain_local }}"
      policy: "one_factor"
    - domain: "srr.{{ domain_local }}"
      policy: "one_factor"
    - domain: "rrr.{{ domain_local }}"
      policy: "one_factor"
    - domain: "prr.{{ domain_local }}"
      policy: "one_factor"
    # piped, homarr, homeassistant

session:
  cookies:
    - domain: "{{ domain_public }}"
      authelia_url: "https://auth.{{ domain_public }}"
      default_redirection_url: "https://www.{{ domain_public }}"
      name: "authelia_session"
      expiration: "3 hours"
      inactivity: "30 minutes"
  redis:
    host: "redis"
    port: 6379

regulation:
  max_retries: 5
  find_time: "2 minutes"
  ban_time: "5 minutes"

storage:
  local:
    path: "/config/db.sqlite3"

notifier:
  smtp:
    address: "smtp://smtp.resend.com"
    timeout: "5s"
    username: "resend"
    password: "{{ mail_notification_api_key }}"
    sender: "Authelia <authelia@notifier.{{ domain_public }}>"
    subject: "🔑 Authelia: {title}"
    disable_require_tls: false
    disable_starttls: false
    disable_html_emails: false

ntp:
  address: "udp://time.cloudflare.com:123"
  version: 3
  max_desync: "3s"
  disable_startup_check: false
  disable_failure: false
