---
- name: Update and upgrade packages on Debian/Ubuntu
  apt:
    update_cache: true
    upgrade: true
    autoremove: true
  when: ansible_os_family == "Debian"

- name: Update and upgrade packages on Fedora
  dnf:
    name: "*"
    state: latest
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot if required
  reboot:
    msg: Rebooting due to a kernel update
  when: reboot_required_file.stat.exists

- name: Install extra packages
  package:
    name: "{{ extra_packages }}"
    state: present

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Show system hostname
  debug:
    msg: "System Hostname: {{ ansible_facts['hostname'] }}"

- name: Replace the hostname entry with own
  lineinfile:
    path: /etc/hosts
    insertafter: ^127\.0\.0\.1 *localhost
    line: "127.0.0.1 {{ inventory_hostname }}"
    owner: root
    group: root
    mode: "0644"

- name: Create user bin directory
  file:
    path: "/home/{{ username }}/bin"
    state: directory
    mode: "0755"
