---
- name: Copy send_notification_mail script to bin directory
  template:
    src: "{{ role_path }}/templates/send_notification_mail.sh"
    dest: "/home/{{ username }}/bin/send_notification_mail.sh"
    mode: "0755"

- name: Create sshrc for ssh login notifications
  template:
    src: "{{ role_path }}/templates/sshrc"
    dest: "/etc/ssh/sshrc"
    owner: root
    group: root
    mode: "0644"

- name: Configure watching over zfs key file
  when: disk_config is defined and disk_config | length > 0
  block:
    - name: Install inotify-tools (includes inotify-watch)
      apt:
        update_cache: true
        name: inotify-tools
        state: present

    - name: Copy watch_zfs_keyfile.sh script to host
      template:
        src: "{{ role_path }}/templates/watch_zfs_keyfile.sh"
        dest: "/usr/local/sbin/watch_zfs_keyfile.sh"
        owner: root
        group: root
        mode: "0700"

    - name: Copy zfs watch service file to host
      template:
        src: "{{ role_path }}/templates/zfs_keyfile_watch.service"
        dest: /etc/systemd/system/zfs_keyfile_watch.service
        mode: "0644"

    - name: Enable zfs watch service file
      systemd:
        name: zfs_keyfile_watch
        enabled: true
        state: started
