---
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    network_mode: "host"
    user: 0:0
    group_add:
      - "{{ gid_render }}"
    volumes:
      - "{{ docker_dir }}/jellyfin/config:/config"
      - "{{ docker_dir }}/jellyfin/cache:/cache"
      - type: bind
        source: "{{ mergerfs_media_dir }}"
        target: /media
        read_only: true
      - type: bind
        source: "{{ nas_mount }}/personal/Music"
        target: /music
        read_only: true
    devices:
      - /dev/dri/renderD128:/dev/dri/renderD128
    environment:
      - JELLYFIN_PublishedServerUrl=http://fin.{{ domain_local }}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8096/health"]
      interval: 2s
      timeout: 60s
      retries: 20
    restart: "unless-stopped"
