---
services:
  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - "{{ docker_dir }}/homeassistant/config:/config"
      - "/etc/localtime:/etc/localtime:ro"
      - "/run/dbus:/run/dbus:ro"
    restart: unless-stopped
    privileged: true
    network_mode: host # port 8123
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8123"]
      interval: 2s
      timeout: 60s
      retries: 20
