---
services:
  openssh-server:
    image: lscr.io/linuxserver/openssh-server:latest
    container_name: scp-target_openssh
    environment:
      - PUID=1000
      - PGID=1000
      - SUDO_ACCESS=false
      - PASSWORD_ACCESS=true
      - USER_PASSWORD_FILE=/secrets/USER_PASSWORD
      - USER_NAME=scp_user
    volumes:
      - "{{ docker_dir }}/scp_target/config:/config"
      - "{{ docker_dir }}/scp_target/secrets:/secrets"
      - "{{ docker_dir }}/scp_target/scripts:/scripts"
      - "{{ docker_dir }}/scp_target/data:/data"
    ports:
      - 2222:2222
    network_mode: "service:tailscale"
    depends_on:
      - tailscale
    restart: unless-stopped

  cron:
    image: whefter/cron
    container_name: scp-target_cron
    network_mode: none
    volumes:
      - "{{ docker_dir }}/scp_target/data:/data"
    environment:
      - "CRON_FREE_UP_SPACE=*/30 * * * * root /scripts/free_up_space.sh"
    restart: unless-stopped

  tailscale:
    image: tailscale/tailscale:latest
    container_name: scp-target_tailscale
    hostname: scp_target-{{ hostname }}
    environment:
      - TS_AUTHKEY={{ scp_target_ts_auth_key }}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERPSACE=false
    volumes:
      - "{{ docker_dir }}/scp_target/tailscale/state:/var/lib/tailscale"
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
