---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: torrenting_gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # for mullvad
      # - VPN_SERVICE_PROVIDER=mullvad
      # - VPN_TYPE=openvpn
      # - OPENVPN_USER="{{ mullvad_user }}""
      # - SERVER_COUNTRIES=Germany,France,Austria
      # - OWNED_ONLY=yes
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=openvpn
      - OPENVPN_CUSTOM_CONFIG=/gluetun/custom.ovpn
      - OPENVPN_USER={{ openvpn_user }}
      - OPENVPN_PASSWORD={{ openvpn_password }}
      - FIREWALL_OUTBOUND_SUBNETS="192.168.178.0/24"
    volumes:
      - "{{ docker_dir }}/gluetun/config/custom.ovpn:/gluetun/custom.ovpn"
    ports:
      - 9191:9091 # transmission web
      - 443:443 # transmission bittorrent
      - 443:443/udp # transmission bittorrent
      - 9696:9696 # prowlarr
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: torrenting_transmission
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - PEERPORT=443
    volumes:
      - "{{ docker_dir }}/transmission/data:/config"
      - "{{ mergerfs_media_dir }}/downloads:/downloads"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 2s
      timeout: 60s
      retries: 20

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: torrenting_prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - "{{ docker_dir }}/prowlarr/data:/config"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 2s
      timeout: 60s
      retries: 20

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: torrenting_sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - "{{ docker_dir }}/sonarr/data:/config"
      - "{{ mergerfs_media_dir }}/shows:/shows"
      - "{{ mergerfs_media_dir }}/downloads:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 2s
      timeout: 60s
      retries: 20

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: torrenting_radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - "{{ docker_dir }}/radarr/data:/config"
      - "{{ mergerfs_media_dir }}/movies:/movies"
      - "{{ mergerfs_media_dir }}/downloads:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 2s
      timeout: 60s
      retries: 20
