---
services:
  gluetun:
    image: qmcgaw/gluetun
    container_name: torrenting_gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    environment:
      # for mullvad
      # - VPN_SERVICE_PROVIDER=mullvad
      # - VPN_TYPE=openvpn
      # - OPENVPN_USER="{{ mullvad_user }}""
      # - SERVER_COUNTRIES=Germany,France,Austria
      # - OWNED_ONLY=yes
      - VPN_SERVICE_PROVIDER=custom
      - VPN_TYPE=wireguard
      - WIREGUARD_ENDPOINT_IP={{ wg_endpoint_ip }}
      - WIREGUARD_ENDPOINT_PORT={{ wg_endpoint_port }}
      - WIREGUARD_PUBLIC_KEY={{ wg_public_key }}
      - WIREGUARD_PRIVATE_KEY={{ wg_private_key }}
      - WIREGUARD_ADDRESSES={{ wg_addresses }}
      - FIREWALL_OUTBOUND_SUBNETS="192.168.178.0/24"
      - FIREWALL_VPN_INPUT_PORTS=54188
    ports:
      - 9191:9091 # transmission web
      - 9696:9696 # prowlarr
    restart: unless-stopped

  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: torrenting_transmission
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
      - PEERPORT=54188
    volumes:
      - "{{ docker_dir }}/transmission/data:/config"
      - "/mnt/media_cache/downloads:/downloads"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 2s
      timeout: 60s
      retries: 20

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: torrenting_prowlarr
    network_mode: "service:gluetun"
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - "{{ docker_dir }}/prowlarr/data:/config"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9696"]
      interval: 2s
      timeout: 60s
      retries: 20

  flaresolverr: # reachable via localhost:8191
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: torrenting_flaresolverr
    network_mode: "service:gluetun"
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=Europe/Berlin
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: torrenting_sonarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - "{{ docker_dir }}/sonarr/data:/config"
      - "{{ mergerfs_media_dir }}/shows:/shows"
      - "{{ mergerfs_media_dir }}/downloads:/downloads"
    ports:
      - 8989:8989
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8989"]
      interval: 2s
      timeout: 60s
      retries: 20

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: torrenting_radarr
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Berlin
    volumes:
      - "{{ docker_dir }}/radarr/data:/config"
      - "{{ mergerfs_media_dir }}/movies:/movies"
      - "{{ mergerfs_media_dir }}/downloads:/downloads"
    ports:
      - 7878:7878
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7878"]
      interval: 2s
      timeout: 60s
      retries: 20
