---
- name: Make sure that the docker folders exists
  file:
    path: "{{ item }}"
    owner: "{{ username }}"
    group: "{{ username }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ docker_compose_dir }}"
    - "{{ docker_dir }}"

- name: Install selected services
  include_tasks: "{{ item }}"
  when: item.split('/')[-1].split('.')[0] in services
  loop:
    - services/authelia.yml
    - services/beszel-agent.yml
    - services/beszel-hub.yml
    - services/caddy.yml
    - services/cloudflare-ddns.yml
    - services/cryptgeon.yml
    - services/dashdot.yml
    - services/homarr.yml
    - services/homeassistant.yml
    - services/immich.yml
    - services/jellyfin.yml
    - services/nextcloud.yml
    - services/piped.yml
    - services/samba.yml
    - services/scp-target.yml
    - services/syncthing.yml
    - services/torrenting.yml
    - services/watchtower.yml

- name: Find all docker compose subdirectores
  find:
    paths: "{{ docker_compose_dir }}"
    file_type: directory
  register: subdirectories

- name: Start every container that exists on host
  community.docker.docker_compose_v2:
    project_src: "{{ item.path }}"
    build: always
  loop: "{{ subdirectories.files }}"
  when: item.path is not none
